[MM-39388] Added IsEnterpriseReady API
mattermost/mattermost-plugin-api pull request #104
Opened 2021-10-19 08:02 UTC by Zeezee1210

#### Summary
Adds the IsEnterpriseReady API from Mattermost-Server

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/MM-39388

2021-10-19 08:04 UTC, Zeezee1210 commented
Hi, 
Not added a test as it seemed a little contrived to mock it.
If you would like a test then please let me know, happy to add whatever you suggest.

2021-10-19 08:05 UTC, Zeezee1210 commented
Also to note:
Still awaiting this [PR](https://github.com/mattermost/mattermost-server/pull/18676) to be merged for this to be available in the server.

2021-10-19 13:41 UTC, lieut-data requested changes

2021-10-21 09:18 UTC, agarciamontoro commented
Thank you again for your contribution, @Zeezee1210! :tada:

2021-10-21 09:18 UTC, merged